[[redirects]]
  from = "/api/*"
  to = "http://103.120.178.99:5001/api/:splat"
  status = 200
  force = true

# Must come AFTER the above
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200